### ISSUE TITLE
Openimmo Xml in english language

### ISSUE THREAD

**Issue by SwatiPatel121** [OpenEstate/OpenEstate-IO#8]
Is this possible to write openimmo xml in eglish language?

**Comment by pinhead84** [comment]
What exactly are you trying to achieve?

1. You want to translate the XML elements and attributes of OpenImmo-XML itself into English language? - This is unfortunately not possible. The standard is provided by the german [OpenImmo e.V.](http://openimmo.de/) (which does not belong to our project). Unfortunately they do not provide an English XML specification (xsd file). We're just following their specifications...

2. You want to transfer real estate data in English language with OpenImmo-XML? - In this case you can just put your English data into the XML structure. But you should make sure, that the recipient of your XML is able to process this data correctly.
